### ISSUE TITLE
Leads - Custom Post Type

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#37]
As a user I want to be able to manage leads within WordPress. As it is supported by the API. I should be able to add, edit, update, and delete leads from within WordPress. 

Future features should include:
* Bulk add leads
* View lead traffic
* View, get, delete notes
* View, get, delete saved properties
* View, get, delete saved searches

**Comment by antonioortegajr** [comment]
Currently this would be very expensive on API calls if you have more than a few users. I think some enhancements need to happen to the API before this is viable. Specifically the addition of data in the normal Leads call to indicate that subsequent calls would have new data on that lead. Otherwise it's an API for each lead and calls to check notes, saved props, etc...

**Comment by bhubbard** [comment]
I wasn't very specific in this request, however I think this is completely possible without doing too many API calls. 

For starters the plugin would make one API call which would grab all the leads. This would provide us enough data to create a Custom Post Type and populate it with basic lead info. In the WordPress Admin UI we can then add buttons or options for the WP User to `get/delete/post/put` for any lead, saved property, saved search, or notes. 

Some users may not be happy, because if they want to quickly download all the saved properties for every lead, and have many leads, they would need to manually request the info thru the WordPress UI for each lead. But I think it is a fair compromise.  If the API ever gets updated then the plugin could be updated to pull all the data for all the leads at once.

**Comment by amcn84** [comment]
Still leaves the door open for end users to go and click all the buttons and throw themselves over the limit. This needs more thought and possibly redesign of the current API method to provide just enough information in 1 call to the API without needing additional calls to gather more information about a lead. Could also link to the IDX Dashboard for a specific lead instead of calling the API.
